/**
 * Generated by @openapi-codegen
 *
 * @version 1.0.0
 */
import * as reactQuery from "@tanstack/react-query";
import { type ApiContext, useApiContext, queryKeyFn } from "./apiContext";
import { deepMerge } from "./apiUtils";
import type * as Fetcher from "./apiFetcher";
import { apiFetch } from "./apiFetcher";

type QueryFnOptions = {
  signal?: AbortController["signal"];
};

export type QueryOperation = {
  path: string;
  operationId: never;
  variables: unknown | reactQuery.SkipToken;
};
