/**
 * Generated by @openapi-codegen
 *
 * @version 1.0.0
 */
export type SignupRequestDTO = {
  username: string;
  /**
   * @format email
   */
  email: string;
  /**
   * @format password
   */
  password: string;
};

export type AuthResponseDTO = {
  token: string;
};

export type LoginRequestDTO = {
  /**
   * @format email
   */
  email: string;
  /**
   * @format password
   */
  password: string;
};

export type UserDTO = {
  username: string;
  /**
   * @format email
   */
  email: string;
};

export type PasswordDTO = {
  /**
   * @format password
   */
  password: string;
};

export type AdvertisementDTO = {
  /**
   * ID
   */
  id: number;
  address: string;
  city: string;
  coordinates: {
    latitude: number;
    longitude: number;
  };
  images: string[];
  description: string;
  dimensions: number;
  numberOfRooms: number;
  energyClass: string;
  additionalServices: string[];
  nearbyPOIs: string[];
  kind: "sale" | "rent";
  price: number;
};

export type AdvertisementsMetricsDTO = {
  totalVisitsRequested: number;
  totalViews: number;
  advertisements: {
    /**
     * ID
     */
    id: number;
    address: string;
    city: string;
    coordinates: {
      latitude: number;
      longitude: number;
    };
    images: string[];
    description: string;
    dimensions: number;
    numberOfRooms: number;
    energyClass: string;
    additionalServices: string[];
    nearbyPOIs: string[];
    kind: "sale" | "rent";
    price: number;
    views: number;
    visits: number;
    offers: number;
  }[];
};

export type SendEmailDTO = {
  agent: UserDTO;
  advertisement: AdvertisementDTO;
};
